export const TEST = 'TEST';
export const INPUT_REG_MEMBER = 'INPUT_REG_MEMBER';
export const RESET_REG_MEMBER = 'RESET_REG_MEMBER';
export const INPUT_ITEM_TO_MEMBER = 'INPUT_ITEM_TO_MEMBER';
export const INPUT_ITEM_TO_MEMBER_RESET = 'INPUT_ITEM_TO_MEMBER_RESET';
